truncate table SRA_Accessions;
truncate table SRA_Run_Members;
truncate table fastq;

-- Create sra table
-- 1. Create a new table called sra.sra_new first;
-- 2. Then insert records to sra.sra_new;
-- 3. Drop table sra.sra_backup if exists
-- 4. Rename sra.sra to sra.sra_backup
-- 5. Rename sra.sra_new to sra.sra

CREATE TABLE IF NOT EXISTS `sra_new` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `SRR_bamFile` varchar(255) character set latin1 default NULL,
  `SRX_bamFile` varchar(255) character set latin1 default NULL,
  `SRX_fastqFTP` varchar(50) character set latin1 default NULL,
  `run_ID` int(10) unsigned default '0',
  `run_alias` varchar(255) character set latin1 default NULL,
  `run_accession` varchar(50) character set latin1 default NULL,
  `run_date` date default NULL,
  `updated_date` date default NULL,
  `spots` bigint(15) default NULL,
  `bases` bigint(15) default NULL,
  -- `run_file` text character set latin1,
  `run_center` varchar(255) character set latin1 default NULL,
  -- `total_data_blocks` int(10) default NULL,
  `experiment_name` varchar(255) character set latin1 default NULL,
  `run_url_link` text character set latin1,
  `run_entrez_link` text character set latin1,
  `run_attribute` text character set latin1,
  `experiment_ID` int(10) unsigned default '0',
  `experiment_alias` varchar(255) character set latin1 default NULL,
  `experiment_accession` varchar(50) character set latin1 default NULL,
  `experiment_title` varchar(255) character set latin1 default NULL,
  `study_name` varchar(255) character set latin1 default NULL,
  `sample_name` varchar(255) character set latin1 default NULL,
  `design_description` text character set latin1,
  `library_name` varchar(255) character set latin1 default NULL,
  `library_strategy` varchar(255) character set latin1 default NULL,
  `library_source` varchar(255) character set latin1 default NULL,
  `library_selection` varchar(255) character set latin1 default NULL,
  `library_layout` varchar(255) character set latin1 default NULL,
  `library_construction_protocol` text character set latin1,
  -- `spot_decode_method` int(5) default NULL,
  --   `number_of_reads_per_spot` int(1) default NULL,
  `adapter_spec` varchar(255) character set latin1 default NULL,
  `read_spec` text character set latin1,
  `platform` varchar(255) character set latin1 default NULL,
  `instrument_model` varchar(255) character set latin1 default NULL,
  `instrument_name` varchar(255) character set latin1 default NULL,
  `platform_parameters` text character set latin1,
  `sequence_space` varchar(255) character set latin1 default NULL,
  `base_caller` varchar(255) character set latin1 default NULL,
  `quality_scorer` varchar(255) character set latin1 default NULL,
  `number_of_levels` int(5) default NULL,
  `multiplier` varchar(255) character set latin1 default NULL,
  `qtype` varchar(50) character set latin1 default NULL,
  `experiment_url_link` text character set latin1,
  `experiment_entrez_link` text character set latin1,
  `experiment_attribute` text character set latin1,
  `sample_ID` int(10) unsigned default '0',
  `sample_alias` varchar(255) character set latin1 default NULL,
  `sample_accession` varchar(50) character set latin1 default NULL,
  `taxon_id` int(10) default NULL,
  `common_name` varchar(255) character set latin1 default NULL,
  `anonymized_name` varchar(255) character set latin1 default NULL,
-- added
  `individual_name` varchar(255) character set latin1 default NULL,
  `description` text character set latin1,
  `sample_url_link` text character set latin1,
  `sample_entrez_link` text character set latin1,
  -- `sample_members` text character set latin1,
  `sample_attribute` text character set latin1,
  `study_ID` int(10) unsigned default '0',
  `study_alias` varchar(255) character set latin1 default NULL,
  `study_accession` varchar(50) character set latin1 default NULL,
  `study_title` varchar(255) character set latin1 default NULL,
  `study_type` varchar(255) character set latin1 default NULL,
  `study_abstract` text character set latin1,
  `center_project_name` varchar(255) character set latin1 default NULL,
  -- `project_id` int(10) default NULL,
  `study_description` text character set latin1,
  `study_url_link` text character set latin1,
  `study_entrez_link` text character set latin1,
  `study_attribute` text character set latin1,
  `related_studies` text character set latin1,
  `primary_study` varchar(10) character set latin1 default NULL,
  `submission_ID` int(10) unsigned NOT NULL default '0',
  `submission_accession` varchar(50) character set latin1 default NULL,
  -- `submission_name` varchar(255) character set latin1 default NULL,
  `submission_comment` text character set latin1,
  `submission_center` varchar(255) character set latin1 default NULL,
  `submission_lab` varchar(255) character set latin1 default NULL,
  `submission_date` date default NULL,
  `sradb_updated` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY  (`ID`),
  KEY `run_alias` (`ID`,`run_alias`),
  KEY `experiment_alias` (`ID`,`experiment_alias`),
  KEY `run_ID` (`run_ID`),
  KEY `experiment_ID` (`experiment_ID`),
  KEY `sample_ID` (`sample_ID`),
  KEY `study_ID` (`study_ID`),
  KEY `submission_ID` (`submission_ID`),
  FULLTEXT KEY `sra_index1` (`sample_alias`,`common_name`,`sample_attribute`,`description`,`study_title`,`study_attribute`,`study_description`,`platform_parameters`,`study_type`,`library_strategy`,`SRR_bamFile`,`run_accession`,`experiment_accession`,`sample_accession`,`study_accession`,`submission_accession`),
  FULLTEXT KEY `sra_index2` (`study_entrez_link`,`platform_parameters`,`design_description`,`experiment_attribute`,`experiment_title`,`library_construction_protocol`,`run_attribute`,`library_selection`,`study_abstract`,`library_source`,`library_layout`,`submission_comment`,`submission_lab`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=1 ;

truncate table `sra_new`;

CREATE TABLE IF NOT EXISTS `sra`.`fastq` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `RUN_ID` varchar(100) character set latin1 default NULL,
  `RUN_ALIAS` varchar(100) character set latin1 default NULL,
  `EXPERIMENT_ID` varchar(100) character set latin1 default NULL,
  `EXPERIMENT_ALIAS` varchar(100) character set latin1 default NULL,
  `SAMPLE_ID` varchar(100) character set latin1 default NULL,
  `SAMPLE_ALIAS` varchar(100) character set latin1 default NULL,
  `STUDY_ID` varchar(100) character set latin1 default NULL,
  `STUDY_ALIAS` varchar(100) character set latin1 default NULL,
  `LIBRARY_LAYOUT` varchar(100) character set latin1 default NULL,
  `INSTRUMENT_PLATFORM` varchar(100) character set latin1 default NULL,
  `STUDY_TYPE` varchar(100) character set latin1 default NULL,
  `FASTQ_FILES` int(2) default NULL,
  `TAX_ID` int(10) default NULL,
  `SCIENTIFIC_NAME` varchar(100) character set latin1 default NULL,
  `COMMON_NAME` varchar(100) character set latin1 default NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=1 ;


